### ISSUE TITLE
Add a default writer (i.e accept content-type) in ResponseWriter

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/SolRDF#30]
16:21:03,081 INFO  [store] webapp=/solr path=/rdf-graph-store params={default=} status=0 QTime=3 
16:21:03,082 ERROR null:org.apache.jena.riot.RiotException: No graph writer for null
	at org.apache.jena.riot.RDFDataMgr.createGraphWriter$(RDFDataMgr.java:1304)
	at org.apache.jena.riot.RDFDataMgr.write$(RDFDataMgr.java:1318)
	at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:1085)
	at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:1075)
	at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:1009)
	at org.gazzax.labs.solrdf.response.SPARQLResponseWriter$3.doWrite(SPARQLResponseWriter.java:139)
	at org.gazzax.labs.solrdf.response.SPARQLResponseWriter.write(SPARQLResponseWriter.java:72)
	at org.apache.solr.servlet.SolrDispatchFilter.writeResponse(SolrDispatchFilter.java:762)

**Comment by agazzarini** [comment]
The issue has been closed as indirect consequence of the "integration test suite" issue. The SparqlResponseWriter implements a delegate logic that, based on the incoming request and the kind of query that has been received, negotiate and determines the appropriate response content type.
