### ISSUE TITLE
SolrRdf running issue

### ISSUE THREAD

**Issue by azeem87** [agazzarini/SolRDF#50]
[INFO] [beddedLocalContainer] Jetty 7.6.15.v20140411 Embedded starting...
2015-04-07 10:12:30.194:INFO:oejs.Server:jetty-7.6.15.v20140411
2015-04-07 10:12:30.243:INFO:oejw.WebInfConfiguration:Extract jar:file:/D:/MavenSpringRepo/org/apache/solr/solr/4.10.3/solr-4.10.3.war!/ to C:\Users\443776\AppData\Local\Temp\jetty-0.0.0.0-8080-solr-4.10.3.war-_solr-any-\webapp
2015-04-07 10:12:40.442:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/solr,file:/C:/Users/443776/AppData/Local/Temp/jetty-0.0.0.0-8080-solr-4.10.3.war-_solr-any-/webapp/},D:\MavenSpringRepo\org\apache\solr\solr\4.10.3\solr-4.10.3.war
log4j:ERROR Could not parse url [file://C:/Users/443776/git/SolRDF/solrdf/src/test/resources/log4j.xml].
java.net.UnknownHostException: C
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:958)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:918)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1013)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:999)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
	at org.apache.log4j.xml.DOMConfigurator$2.parse(DOMConfigurator.java:765)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:871)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at org.apache.solr.servlet.CheckLoggingConfiguration.check(CheckLoggingConfiguration.java:26)
	at org.apache.solr.servlet.BaseSolrFilter.<clinit>(BaseSolrFilter.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createFilter(ServletContextHandler.java:592)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:93)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:707)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:254)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1240)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:482)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:281)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.cargo.container.jetty.internal.JettyExecutorThread.run(JettyExecutorThread.java:69)
log4j:WARN No appenders could be found for logger (org.apache.solr.client.solrj.impl.HttpClientUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2015-04-07 10:12:59.221:INFO:oejw.WebInfConfiguration:Extract jar:file:/C:/Users/443776/git/SolRDF/solrdf/target/cargo/configurations/jetty7x/cargocpc.war!/ to C:\Users\443776\AppData\Local\Temp\jetty-0.0.0.0-8080-cargocpc.war-_cargocpc-any-\webapp
2015-04-07 10:13:00.265:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/cargocpc,file:/C:/Users/443776/AppData/Local/Temp/jetty-0.0.0.0-8080-cargocpc.war-_cargocpc-any-/webapp/},C:\Users\443776\git\SolRDF\solrdf\target\cargo\configurations\jetty7x\cargocpc.war
2015-04-07 10:13:03.720:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
[INFO] [beddedLocalContainer] Jetty 7.6.15.v20140411 Embedded started on port [8080]
[INFO] Press Ctrl-C to stop the container...

**Comment by azeem87** [comment]
i am able to see the jetty port running, but after this i am not able to push rdf sample data in test/resources folder.

**Comment by azeem87** [comment]
i am testing in windows machine. project imported in ecplise

**Comment by agazzarini** [comment]
Thanks for entering this issue. I'm working on this. 
It has to do with the windows path of the log4j configuration file. I fixed that in my locale environment, but I have to test it with Windows so, just a little bit to setup a VM and I will let you know.

**Comment by azeem87** [comment]
thanks for your contribution. eagarly waiting for the update.

**Comment by agazzarini** [comment]
Ok, close, the latest version of master contains the fix

@azeem87 Note that if you're on Eclipse I prepared a ready-to-use Maven launch configuration. You can find that under $PROJECT_HOME/solrdf/src/dev/eclipse

Just right click on them and select Debug As >> start-SolRDF

IMPORTANT: as you can see I used "Debug As" instead of "Run As". That is because of an annoying bug on Eclipse, which sometimes, when using a "Run configuration", is no longer able to kill the process. So if you try to stop it, most probably it will fail and it will leave an orphan process. So briefly, just use "Debug As"

**Comment by azeem87** [comment]
thanks , now i am able to run the code..
