### ISSUE TITLE
 java.text.ParseException: Unparseable date: "2008-06-08"

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/SolRDF#94]
Using the BSBM generated dataset, the following query, that involves a DateTime datatype:

```
SELECT * 
WHERE {     
?s <http://purl.org/dc/elements/1.1/date> ?o .     
?s <http://purl.org/dc/elements/1.1/publisher> ?o.    
}   
```
Raises the following exception: 

```
Caused by: java.text.ParseException: Unparseable date: "2008-06-08"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at org.gazzax.labs.solrdf.graph.standalone.FieldInjectorRegistry$4.addFilterConstraint(FieldInjectorRegistry.java:120)
	... 53 more
```

The problem seems to be the DateFormat used in FieldInjectionRegistry, which doesn't allow optional parts in date pattern.

VIP: This error has been detected on the local graph family, and once fixed, should be applied also to cloud family.

**Comment by agazzarini** [comment]
Issue has been fixed in "issue_89" branch...I will merge that tomorrow

**Comment by agazzarini** [comment]
Pull request, related with this issue, from branch "issue_89" has been merged
